namespace Wholesome_Auto_Quester.Database.Models
{
    public class ModelSpell
    {
        public int Id { get; set; }
        public int category { get; set; }
        public int dispelType { get; set; }
        public int mechanic { get; set; }
        public int attributes { get; set; }
        public int attributesEx { get; set; }
        public int attributesExB { get; set; }
        public int attributesExC { get; set; }
        public int attributesExD { get; set; }
        public int attributesExE { get; set; }
        public int attributesExF { get; set; }
        public int attributesExG { get; set; }
        public int shapeshiftMask { get; set; }
        public int shapeshiftExclude { get; set; }
        public int targets { get; set; }
        public int targetCreatureType { get; set; }
        public int requiresSpellFocus { get; set; }
        public int facingCasterFlags { get; set; }
        public int casterAuraState { get; set; }
        public int targetAuraState { get; set; }
        public int excludeCasterAuraState { get; set; }
        public int excludeTargetAuraState { get; set; }
        public int casterAuraSpell { get; set; }
        public int targetAuraSpell { get; set; }
        public int excludeCasterAuraSpell { get; set; }
        public int excludeTargetAuraSpell { get; set; }
        public int castingTimeIndex { get; set; }
        public int recoveryTime { get; set; }
        public int categoryRecoveryTime { get; set; }
        public int interruptFlags { get; set; }
        public int auraInterruptFlags { get; set; }
        public int channelInterruptFlags { get; set; }
        public int procTypeMask { get; set; }
        public int procChance { get; set; }
        public int procCharges { get; set; }
        public int maxLevel { get; set; }
        public int baseLevel { get; set; }
        public int spellLevel { get; set; }
        public int durationIndex { get; set; }
        public int powerType { get; set; }
        public int manaCost { get; set; }
        public int manaCostPerLevel { get; set; }
        public int manaPerSecond { get; set; }
        public int manaPerSecondPerLevel { get; set; }
        public int rangeIndex { get; set; }
        public int speed { get; set; }
        public int modalNextSpell { get; set; }
        public int cumulativeAura { get; set; }
        public int tote1 { get; set; }
        public int tote2 { get; set; }
        public int reagent_1 { get; set; }
        public int reagent_2 { get; set; }
        public int reagent_3 { get; set; }
        public int reagent_4 { get; set; }
        public int reagent_5 { get; set; }
        public int reagent_6 { get; set; }
        public int reagent_7 { get; set; }
        public int reagent_8 { get; set; }
        public int reagentCount_1 { get; set; }
        public int reagentCount_2 { get; set; }
        public int reagentCount_3 { get; set; }
        public int reagentCount_4 { get; set; }
        public int reagentCount_5 { get; set; }
        public int reagentCount_6 { get; set; }
        public int reagentCount_7 { get; set; }
        public int reagentCount_8 { get; set; }
        public int equippedItemClass { get; set; }
        public int equippedItemSubclass { get; set; }
        public int equippedItemInvTypes { get; set; }
        public int effect_1 { get; set; }
        public int effect_2 { get; set; }
        public int effect_3 { get; set; }
        public int effectDieSides_1 { get; set; }
        public int effectDieSides_2 { get; set; }
        public int effectDieSides_3 { get; set; }
        public int effectRealPointsPerLevel_1 { get; set; }
        public int effectRealPointsPerLevel_2 { get; set; }
        public int effectRealPointsPerLevel_3 { get; set; }
        public int effectBasePoints_1 { get; set; }
        public int effectBasePoints_2 { get; set; }
        public int effectBasePoints_3 { get; set; }
        public int effectMechanic_1 { get; set; }
        public int effectMechanic_2 { get; set; }
        public int effectMechanic_3 { get; set; }
        public int implicitTargetA_1 { get; set; }
        public int implicitTargetA_2 { get; set; }
        public int implicitTargetA_3 { get; set; }
        public int implicitTargetB_1 { get; set; }
        public int implicitTargetB_2 { get; set; }
        public int implicitTargetB_3 { get; set; }
        public int effectRadiusIndex_1 { get; set; }
        public int effectRadiusIndex_2 { get; set; }
        public int effectRadiusIndex_3 { get; set; }
        public int effectAura_1 { get; set; }
        public int effectAura_2 { get; set; }
        public int effectAura_3 { get; set; }
        public int effectAuraPeriod_1 { get; set; }
        public int effectAuraPeriod_2 { get; set; }
        public int effectAuraPeriod_3 { get; set; }
        public int effectAmplitude_1 { get; set; }
        public int effectAmplitude_2 { get; set; }
        public int effectAmplitude_3 { get; set; }
        public int effectChainTargets_1 { get; set; }
        public int effectChainTargets_2 { get; set; }
        public int effectChainTargets_3 { get; set; }
        public int effectItemType_1 { get; set; }
        public int effectItemType_2 { get; set; }
        public int effectItemType_3 { get; set; }
        public int effectMiscValue_1 { get; set; }
        public int effectMiscValue_2 { get; set; }
        public int effectMiscValue_3 { get; set; }
        public int effectMiscValueB_1 { get; set; }
        public int effectMiscValueB_2 { get; set; }
        public int effectMiscValueB_3 { get; set; }
        public int effectTriggerSpell_1 { get; set; }
        public int effectTriggerSpell_2 { get; set; }
        public int effectTriggerSpell_3 { get; set; }
        public int effectPointsPerCombo_1 { get; set; }
        public int effectPointsPerCombo_2 { get; set; }
        public int effectPointsPerCombo_3 { get; set; }
        public int effectSpellClassMaskA_1 { get; set; }
        public int effectSpellClassMaskA_2 { get; set; }
        public int effectSpellClassMaskA_3 { get; set; }
        public int effectSpellClassMaskB_1 { get; set; }
        public int effectSpellClassMaskB_2 { get; set; }
        public int effectSpellClassMaskB_3 { get; set; }
        public int effectSpellClassMaskC_1 { get; set; }
        public int effectSpellClassMaskC_2 { get; set; }
        public int effectSpellClassMaskC_3 { get; set; }
        public int spellVisualID_1 { get; set; }
        public int spellVisualID_2 { get; set; }
        public int spellIconID { get; set; }
        public int activeIconID { get; set; }
        public int spellPriority { get; set; }
        public int name_flag { get; set; }
        public string name_lang_1 { get; set; }
        public int nameSubtext_flag { get; set; }
        public string nameSubtext_lang_1 { get; set; }
        public int description_flag { get; set; }
        public string description_lang_1 { get; set; }
        public int auraDescription_flag { get; set; }
        public string auraDescription_lang_1 { get; set; }
        public int manaCostPct { get; set; }
        public int startRecoveryCategory { get; set; }
        public int startRecoveryTime { get; set; }
        public int maxTargetLevel { get; set; }
        public int spellClassSet { get; set; }
        public int spellClassMask_1 { get; set; }
        public int spellClassMask_2 { get; set; }
        public int spellClassMask_3 { get; set; }
        public int maxTargets { get; set; }
        public int defenseType { get; set; }
        public int preventionType { get; set; }
        public int stanceBarOrder { get; set; }
        public int effectChainAmplitude_1 { get; set; }
        public int effectChainAmplitude_2 { get; set; }
        public int effectChainAmplitude_3 { get; set; }
        public int minFactionID { get; set; }
        public int minReputation { get; set; }
        public int requiredAuraVision { get; set; }
        public int requiredTotemCategoryID_1 { get; set; }
        public int requiredTotemCategoryID_2 { get; set; }
        public int requiredAreasID { get; set; }
        public int schoolMask { get; set; }
        public int runeCostID { get; set; }
        public int spellMissileID { get; set; }
        public int powerDisplayID { get; set; }
        public int unk1_1 { get; set; }
        public int unk1_2 { get; set; }
        public int unk1_3 { get; set; }
        public int spellDescriptionVariableID { get; set; }
        public int spellDifficultyID { get; set; }
    }
}
